
export interface BibleBook {
    index: number;    // 1-based, matches file prefix
    name: string;     // Display name (Spanish)
    chapters: number; // Total chapters
    testament: 'AT' | 'NT';
}

export const BIBLE_BOOKS: BibleBook[] = [
    // Antiguo Testamento
    { index: 1,  name: 'Génesis',          chapters: 50,  testament: 'AT' },
    { index: 2,  name: 'Éxodo',            chapters: 40,  testament: 'AT' },
    { index: 3,  name: 'Levítico',         chapters: 27,  testament: 'AT' },
    { index: 4,  name: 'Números',          chapters: 36,  testament: 'AT' },
    { index: 5,  name: 'Deuteronomio',     chapters: 34,  testament: 'AT' },
    { index: 6,  name: 'Josué',            chapters: 24,  testament: 'AT' },
    { index: 7,  name: 'Jueces',           chapters: 21,  testament: 'AT' },
    { index: 8,  name: 'Rut',              chapters: 4,   testament: 'AT' },
    { index: 9,  name: '1 Samuel',         chapters: 31,  testament: 'AT' },
    { index: 10, name: '2 Samuel',         chapters: 24,  testament: 'AT' },
    { index: 11, name: '1 Reyes',          chapters: 22,  testament: 'AT' },
    { index: 12, name: '2 Reyes',          chapters: 25,  testament: 'AT' },
    { index: 13, name: '1 Crónicas',       chapters: 29,  testament: 'AT' },
    { index: 14, name: '2 Crónicas',       chapters: 36,  testament: 'AT' },
    { index: 15, name: 'Esdras',           chapters: 10,  testament: 'AT' },
    { index: 16, name: 'Nehemías',         chapters: 13,  testament: 'AT' },
    { index: 17, name: 'Ester',            chapters: 10,  testament: 'AT' },
    { index: 18, name: 'Job',              chapters: 42,  testament: 'AT' },
    { index: 19, name: 'Salmos',           chapters: 150, testament: 'AT' },
    { index: 20, name: 'Proverbios',       chapters: 31,  testament: 'AT' },
    { index: 21, name: 'Eclesiastés',      chapters: 12,  testament: 'AT' },
    { index: 22, name: 'Cantares',         chapters: 8,   testament: 'AT' },
    { index: 23, name: 'Isaías',           chapters: 66,  testament: 'AT' },
    { index: 24, name: 'Jeremías',         chapters: 52,  testament: 'AT' },
    { index: 25, name: 'Lamentaciones',    chapters: 5,   testament: 'AT' },
    { index: 26, name: 'Ezequiel',         chapters: 48,  testament: 'AT' },
    { index: 27, name: 'Daniel',           chapters: 12,  testament: 'AT' },
    { index: 28, name: 'Oseas',            chapters: 14,  testament: 'AT' },
    { index: 29, name: 'Joel',             chapters: 3,   testament: 'AT' },
    { index: 30, name: 'Amós',             chapters: 9,   testament: 'AT' },
    { index: 31, name: 'Abdías',           chapters: 1,   testament: 'AT' },
    { index: 32, name: 'Jonás',            chapters: 4,   testament: 'AT' },
    { index: 33, name: 'Miqueas',          chapters: 7,   testament: 'AT' },
    { index: 34, name: 'Nahúm',            chapters: 3,   testament: 'AT' },
    { index: 35, name: 'Habacuc',          chapters: 3,   testament: 'AT' },
    { index: 36, name: 'Sofonías',         chapters: 3,   testament: 'AT' },
    { index: 37, name: 'Hageo',            chapters: 2,   testament: 'AT' },
    { index: 38, name: 'Zacarías',         chapters: 14,  testament: 'AT' },
    { index: 39, name: 'Malaquías',        chapters: 4,   testament: 'AT' },
    // Nuevo Testamento
    { index: 40, name: 'Mateo',            chapters: 28,  testament: 'NT' },
    { index: 41, name: 'Marcos',           chapters: 16,  testament: 'NT' },
    { index: 42, name: 'Lucas',            chapters: 24,  testament: 'NT' },
    { index: 43, name: 'Juan',             chapters: 21,  testament: 'NT' },
    { index: 44, name: 'Hechos',           chapters: 28,  testament: 'NT' },
    { index: 45, name: 'Romanos',          chapters: 16,  testament: 'NT' },
    { index: 46, name: '1 Corintios',      chapters: 16,  testament: 'NT' },
    { index: 47, name: '2 Corintios',      chapters: 13,  testament: 'NT' },
    { index: 48, name: 'Gálatas',          chapters: 6,   testament: 'NT' },
    { index: 49, name: 'Efesios',          chapters: 6,   testament: 'NT' },
    { index: 50, name: 'Filipenses',       chapters: 4,   testament: 'NT' },
    { index: 51, name: 'Colosenses',       chapters: 4,   testament: 'NT' },
    { index: 52, name: '1 Tesalonicenses', chapters: 5,   testament: 'NT' },
    { index: 53, name: '2 Tesalonicenses', chapters: 3,   testament: 'NT' },
    { index: 54, name: '1 Timoteo',        chapters: 6,   testament: 'NT' },
    { index: 55, name: '2 Timoteo',        chapters: 4,   testament: 'NT' },
    { index: 56, name: 'Tito',             chapters: 3,   testament: 'NT' },
    { index: 57, name: 'Filemón',          chapters: 1,   testament: 'NT' },
    { index: 58, name: 'Hebreos',          chapters: 13,  testament: 'NT' },
    { index: 59, name: 'Santiago',         chapters: 5,   testament: 'NT' },
    { index: 60, name: '1 Pedro',          chapters: 5,   testament: 'NT' },
    { index: 61, name: '2 Pedro',          chapters: 3,   testament: 'NT' },
    { index: 62, name: '1 Juan',           chapters: 5,   testament: 'NT' },
    { index: 63, name: '2 Juan',           chapters: 1,   testament: 'NT' },
    { index: 64, name: '3 Juan',           chapters: 1,   testament: 'NT' },
    { index: 65, name: 'Judas',            chapters: 1,   testament: 'NT' },
    { index: 66, name: 'Apocalipsis',      chapters: 22,  testament: 'NT' },
];

export const VERSIONS = [
    { folder: 'rvr1960',  label: 'RVR1960' },
    { folder: 'ntv',      label: 'NTV' },
    { folder: 'rvr2015',  label: 'RVR2015' },
];
